--データベース作成(既に同名のデータベースがあれば削除する)
CREATE OR REPLACE DATABASE RPG_DB;
--データベースの切替
USE RPG_DB;

--テーブルの作成
--メンバーテーブル
CREATE OR REPLACE TABLE メンバー (
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
名前 VARCHAR(20) NOT NULL,
職業ID INTEGER NOT NULL,
装備ID INTEGER NOT NULL,
攻撃力  INTEGER NOT NULL,
防御力  INTEGER NOT NULL,
備考 VARCHAR(140)
);

--装備テーブル
CREATE OR REPLACE TABLE 装備 (
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
メンバーID INTEGER NOT NULL,
武器ID INTEGER NOT NULL DEFAULT 0,
盾ID INTEGER NOT NULL DEFAULT 0,
防具ID INTEGER NOT NULL DEFAULT 0,
備考 VARCHAR(140)
);

--武器テーブル
CREATE OR REPLACE TABLE 武器 (
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
名称 VARCHAR(20) NOT NULL,
攻撃力 INTEGER NOT NULL DEFAULT 0,
防御力 INTEGER NOT NULL DEFAULT 0,
武器制限 INTEGER NOT NULL DEFAULT 0,
備考 VARCHAR(140)
);

--防具テーブル
CREATE OR REPLACE TABLE 防具 (
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
名称 VARCHAR(20) NOT NULL,
攻撃力 INTEGER NOT NULL DEFAULT 0,
防御力 INTEGER NOT NULL DEFAULT 0,
着用FL INTEGER NOT NULL DEFAULT 0,
防具制限 INTEGER NOT NULL DEFAULT 0,
備考 VARCHAR(140)
);

--職業テーブル
CREATE OR REPLACE TABLE 職業 (
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
名称 VARCHAR(20) NOT NULL,
防具制限 INTEGER NOT NULL DEFAULT 0,
備考 VARCHAR(140)
);

--テーブル確認
SHOW TABLES;

--テーブル設定値確認
DESCRIBE メンバー;
DESCRIBE 装備;
DESCRIBE 武器;
DESCRIBE 防具;
DESCRIBE 職業;
